language: java
dist: trusty
sudo: false
addons:
  chrome: stable      
jdk:
  - oraclejdk8
script:
  - mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarcloud.io
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'